import { sqliteTable, text, integer } from "drizzle-orm/sqlite-core";

// Invoices — the workshop's domain table.
// `amount` is stored in cents (integer) to avoid floating-point money bugs.
export const invoices = sqliteTable("invoices", {
  id: text("id")
    .primaryKey()
    .$defaultFn(() => crypto.randomUUID()),
  // Sequential, human-friendly invoice number (rendered as INV-0001).
  number: integer("number").notNull().unique(),
  customerName: text("customer_name").notNull(),
  customerEmail: text("customer_email").notNull(),
  amount: integer("amount").notNull(),
  status: text("status", { enum: ["pending", "paid"] })
    .notNull()
    .default("pending"),
  // ISO date string (YYYY-MM-DD) — keeps SQLite storage simple and sortable.
  date: text("date").notNull(),
});

export type Invoice = typeof invoices.$inferSelect;
export type NewInvoice = typeof invoices.$inferInsert;

// Customers — standalone table for the Customers section. (Invoices keep the
// customer name/email inline; relating them is a nice follow-up exercise.)
export const customers = sqliteTable("customers", {
  id: text("id")
    .primaryKey()
    .$defaultFn(() => crypto.randomUUID()),
  name: text("name").notNull(),
  email: text("email").notNull(),
  createdAt: integer("created_at", { mode: "timestamp" })
    .$defaultFn(() => new Date())
    .notNull(),
});

export type Customer = typeof customers.$inferSelect;
export type NewCustomer = typeof customers.$inferInsert;

// better-auth tables (user, session, account, verification) are generated by
// the better-auth CLI into ./auth-schema.ts and re-exported here so a single
// `import * as schema from "@/lib/schema"` covers the whole database.
export * from "./auth-schema";
